# Generated by Django 6.0.2 on 2026-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0004_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('renter', 'Car Owner')], default='customer', max_length=20),
        ),
    ]
