# Generated by Django 6.0.2 on 2026-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0008_brand_remove_profile_role_profile_is_renter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
