# Generated by Django 6.0.2 on 2026-06-20 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0011_car_insurance_doc_car_puc_certificate_car_rc_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Currently Booked'), ('maintenance', 'Under Maintenance'), ('verification_pending', 'Pending Verification')], default='verification_pending', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='weekly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='government_id_file',
            field=models.FileField(blank=True, null=True, upload_to='govt_ids/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('advance_paid', 'Advance Paid'), ('awaiting_renter_confirmation', 'Awaiting Renter Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected by Renter'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=40),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CarRental.car')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('booking_submitted', 'Booking Submitted'), ('booking_confirmed', 'Booking Confirmed'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('refund_issued', 'Refund Issued'), ('booking_request', 'New Booking Request'), ('vehicle_approved', 'Vehicle Approved'), ('vehicle_rejected', 'Vehicle Rejected'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarRental.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
